### ISSUE TITLE
Sugestão na página de projetos

### ISSUE THREAD

**Issue by wellissongomes** [lucasmedeiros/portfolio#12]
Ta muito legal seu portifolio, @lucasmedeiros. Parabéns.

Quando nós clicamos em _**ver projetos**_, ainda fica o mesmo botão mesmo quando nós já estamos na página de projetos. Não seria legal o botão 'sumir' quando fossemos para os projetos?

![image](https://user-images.githubusercontent.com/43709693/79272071-4611c880-7e77-11ea-93ad-2959ca60f4ef.png)

**Comment by lucasmedeiros** [comment]
Obrigado pela sugestão! Vou dar uma olhada nisso esse fim de semana =D

**Comment by lucasmedeiros** [comment]
Resolvido [nesse commit](https://github.com/lucasmedeiros/portfolio/commit/c75af1c336dcaf56473486f5c9eb3db291d5f592). Mais uma vez, obrigado pela sugestão! :smile:
